# Auto add reviews and assignees for SOP

addReviewers: true
addAssignees: true

# reviewers should be VATPRC3, VATPRC5 and corresponding assistants
reviewers:
  - paul891014
  - RudiZhang

numberOfReviewers: 0
numberOfAssignees: 0
