name: Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-node@v4
        with: { node-version: "lts/*" }
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: |
          pnpm install
      - name: Build
        run: |
          pnpm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 21001a1efbe4155f55f64e486e2cfe2a
          projectName: vatprc-docs
          directory: dist
